// scripts/sync-fpl.mjs
import fs from 'fs';
import path from 'path';

const FPL_URL = 'https://fantasy.premierleague.com/api/bootstrap-static/';

async function sync() {
  console.log('⚡ Fetching live FPL data...');
  const res = await fetch(FPL_URL);
  if (!res.ok) throw new Error(`FPL API returned ${res.status}`);
  const data = await res.json();

  const teams = data.teams.reduce((acc, t) => {
    acc[t.id] = { name: t.name, short: t.short_name };
    return acc;
  }, {});

  const posMap = { 1: 'GKP', 2: 'DEF', 3: 'MID', 4: 'FWD' };

  // Stable pseudo-random FDR generator based on team ID (no fixtures API needed)
  const seedRandom = (seed) => {
    let x = Math.sin(seed) * 10000;
    return x - Math.floor(x);
  };

  const generateFdrs = (teamId) => {
    return Array.from({ length: 5 }, (_, i) => {
      const rand = seedRandom(teamId * 137 + i + 1); 
      return Math.floor(rand * 5) + 1; // Returns 1 to 5
    });
  };

  // Allow players with 0 minutes (early season)
  const activePlayers = data.elements.filter(p => p.minutes >= 0); 

  const mappedPlayers = activePlayers.map(p => {
    const pos = posMap[p.element_type];
    const per90 = Math.max(p.minutes / 90, 1); // Prevent division by zero
    
    const xg = pos === 'GKP' ? 0 : Number((p.goals_scored / per90 * 0.85).toFixed(2));
    const xa = pos === 'GKP' ? 0 : Number((p.assists / per90 * 0.85).toFixed(2));
    const xs = pos === 'GKP' ? Number((p.saves / per90).toFixed(1)) : undefined;

    // UNIQUE ID FIX: Appends FPL's internal numeric ID to prevent "Henderson" collisions
    const slug = p.web_name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const id = `${slug}-${p.id}`; 
    
    const tag = (
      (p.first_name?.[0] ?? p.web_name[0]) +
      (p.second_name?.[0] ?? p.web_name[1] ?? '')
    ).toUpperCase();

    const fdrs = generateFdrs(p.team);

    return {
      id,
      name: p.web_name,
      tag,
      club: teams[p.team].short,
      pos,
      price: p.now_cost / 10,
      form: parseFloat(p.form) || 0,
      fdr: fdrs[0], // GW1 FDR
      fdrs,         // 5-week lookahead
      xg,
      xa,
      xs,
      own: p.selected_by_percent ? parseFloat(p.selected_by_percent) : 0,
    };
  });

  mappedPlayers.sort((a, b) => (b.form * b.price) - (a.form * a.price));
  const finalPool = mappedPlayers.slice(0, 150);

  const tsContent = `// AUTO-GENERATED BY scripts/sync-fpl.mjs - DO NOT EDIT MANUALLY
import type { Player } from './players.types';

export const PLAYERS: Player[] = ${JSON.stringify(finalPool, null, 2)};
`;

  const outPath = path.join(process.cwd(), 'src/data/players.generated.ts');
  fs.writeFileSync(outPath, tsContent);
  console.log(`✅ Synced ${finalPool.length} players to ${outPath}`);
}

sync().catch(console.error);