// AUTO-GENERATED BY scripts/sync-fpl.mjs - DO NOT EDIT MANUALLY
import type { Player } from './players.types';

export const PLAYERS: Player[] = [
  {
    "id": "raya-1",
    "name": "Raya",
    "tag": "DR",
    "club": "ARS",
    "pos": "GKP",
    "price": 6,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "xs": 1.6,
    "own": 36.5
  },
  {
    "id": "arrizabalaga-2",
    "name": "Arrizabalaga",
    "tag": "KA",
    "club": "ARS",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2,
    "own": 0.1
  },
  {
    "id": "meslier-3",
    "name": "Meslier",
    "tag": "IM",
    "club": "ARS",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "xs": 0,
    "own": 0
  },
  {
    "id": "gabriel-4",
    "name": "Gabriel",
    "tag": "GD",
    "club": "ARS",
    "pos": "DEF",
    "price": 8,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.08,
    "xa": 0.14,
    "own": 29.7
  },
  {
    "id": "j-timber-5",
    "name": "J.Timber",
    "tag": "JT",
    "club": "ARS",
    "pos": "DEF",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.09,
    "xa": 0.19,
    "own": 0.2
  },
  {
    "id": "saliba-6",
    "name": "Saliba",
    "tag": "WS",
    "club": "ARS",
    "pos": "DEF",
    "price": 6,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.03,
    "xa": 0,
    "own": 0.3
  },
  {
    "id": "lewis-skelly-7",
    "name": "Lewis-Skelly",
    "tag": "ML",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.6
  },
  {
    "id": "calafiori-8",
    "name": "Calafiori",
    "tag": "RC",
    "club": "ARS",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.05,
    "xa": 0.09,
    "own": 32.9
  },
  {
    "id": "hincapie-9",
    "name": "Hincapie",
    "tag": "PH",
    "club": "ARS",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.04,
    "xa": 0.09,
    "own": 2.3
  },
  {
    "id": "white-10",
    "name": "White",
    "tag": "BW",
    "club": "ARS",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0.11,
    "own": 3.6
  },
  {
    "id": "mosquera-11",
    "name": "Mosquera",
    "tag": "CM",
    "club": "ARS",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 8.5
  },
  {
    "id": "saka-12",
    "name": "Saka",
    "tag": "BS",
    "club": "ARS",
    "pos": "MID",
    "price": 9.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.24,
    "xa": 0.34,
    "own": 9.3
  },
  {
    "id": "rice-13",
    "name": "Rice",
    "tag": "DR",
    "club": "ARS",
    "pos": "MID",
    "price": 7.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.1,
    "xa": 0.22,
    "own": 19
  },
  {
    "id": "eze-14",
    "name": "Eze",
    "tag": "EE",
    "club": "ARS",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.28,
    "xa": 0.12,
    "own": 2.2
  },
  {
    "id": "-degaard-15",
    "name": "Ødegaard",
    "tag": "MØ",
    "club": "ARS",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.06,
    "xa": 0.39,
    "own": 6.7
  },
  {
    "id": "madueke-16",
    "name": "Madueke",
    "tag": "NM",
    "club": "ARS",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.19,
    "xa": 0.06,
    "own": 0.3
  },
  {
    "id": "merino-17",
    "name": "Merino",
    "tag": "MM",
    "club": "ARS",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.3,
    "xa": 0.22,
    "own": 0.8
  },
  {
    "id": "martinelli-18",
    "name": "Martinelli",
    "tag": "GM",
    "club": "ARS",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.07,
    "xa": 0.36,
    "own": 0.2
  },
  {
    "id": "zubimendi-19",
    "name": "Zubimendi",
    "tag": "MZ",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.13,
    "xa": 0.03,
    "own": 1.2
  },
  {
    "id": "dowman-20",
    "name": "Dowman",
    "tag": "MD",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.5,
    "xa": 0.5,
    "own": 0.1
  },
  {
    "id": "nwaneri-22",
    "name": "Nwaneri",
    "tag": "EN",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "f-bio-vieira-23",
    "name": "Fábio Vieira",
    "tag": "FF",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "nelson-24",
    "name": "Nelson",
    "tag": "RN",
    "club": "ARS",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0.65,
    "own": 0
  },
  {
    "id": "gy-keres-25",
    "name": "Gyökeres",
    "tag": "VG",
    "club": "ARS",
    "pos": "FWD",
    "price": 7.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.48,
    "xa": 0.03,
    "own": 10
  },
  {
    "id": "havertz-26",
    "name": "Havertz",
    "tag": "KH",
    "club": "ARS",
    "pos": "FWD",
    "price": 7.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.27,
    "xa": 0.4,
    "own": 4.8
  },
  {
    "id": "g-jesus-27",
    "name": "G.Jesus",
    "tag": "GF",
    "club": "ARS",
    "pos": "FWD",
    "price": 6,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.55,
    "xa": 0,
    "own": 0.4
  },
  {
    "id": "bruno-g--452",
    "name": "Bruno G.",
    "tag": "BG",
    "club": "ARS",
    "pos": "MID",
    "price": 7,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0.28,
    "xa": 0.22,
    "own": 7.9
  },
  {
    "id": "tzolis-557",
    "name": "Tzolis",
    "tag": "CT",
    "club": "ARS",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 3,
    "fdrs": [
      3,
      5,
      2,
      4,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 20.1
  },
  {
    "id": "martinez-28",
    "name": "Martinez",
    "tag": "EM",
    "club": "AVL",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "xs": 3,
    "own": 4.6
  },
  {
    "id": "m-bizot-29",
    "name": "M.Bizot",
    "tag": "MB",
    "club": "AVL",
    "pos": "GKP",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2.9,
    "own": 0.1
  },
  {
    "id": "digne-30",
    "name": "Digne",
    "tag": "LD",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.29,
    "own": 0.3
  },
  {
    "id": "konsa-31",
    "name": "Konsa",
    "tag": "EK",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.03,
    "own": 15.7
  },
  {
    "id": "cash-32",
    "name": "Cash",
    "tag": "MC",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.08,
    "xa": 0.08,
    "own": 8.5
  },
  {
    "id": "mings-33",
    "name": "Mings",
    "tag": "TM",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.06,
    "own": 0.3
  },
  {
    "id": "pau-34",
    "name": "Pau",
    "tag": "PT",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.09,
    "own": 0.4
  },
  {
    "id": "bogarde-35",
    "name": "Bogarde",
    "tag": "LB",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "maatsen-36",
    "name": "Maatsen",
    "tag": "IM",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.05,
    "own": 0.9
  },
  {
    "id": "lindel-f-37",
    "name": "Lindelöf",
    "tag": "VL",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.08,
    "own": 0.2
  },
  {
    "id": "a-garc-a-38",
    "name": "A.García",
    "tag": "AG",
    "club": "AVL",
    "pos": "DEF",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 1.7
  },
  {
    "id": "nedeljkovic-39",
    "name": "Nedeljkovic",
    "tag": "KN",
    "club": "AVL",
    "pos": "DEF",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.6
  },
  {
    "id": "buend-a-41",
    "name": "Buendía",
    "tag": "EB",
    "club": "AVL",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.26,
    "xa": 0.09,
    "own": 1.4
  },
  {
    "id": "bailey-44",
    "name": "Bailey",
    "tag": "LB",
    "club": "AVL",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0.34,
    "own": 0.1
  },
  {
    "id": "mcginn-45",
    "name": "McGinn",
    "tag": "JM",
    "club": "AVL",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.18,
    "xa": 0.14,
    "own": 3.3
  },
  {
    "id": "barkley-46",
    "name": "Barkley",
    "tag": "RB",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.27,
    "xa": 0.18,
    "own": 0.2
  },
  {
    "id": "kamara-47",
    "name": "Kamara",
    "tag": "BK",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.05,
    "xa": 0.16,
    "own": 0.3
  },
  {
    "id": "onana-48",
    "name": "Onana",
    "tag": "AO",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.09,
    "xa": 0,
    "own": 0
  },
  {
    "id": "iling-jr-49",
    "name": "Iling Jr",
    "tag": "SI",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "burrowes-50",
    "name": "Burrowes",
    "tag": "BB",
    "club": "AVL",
    "pos": "MID",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.7
  },
  {
    "id": "george-hemmings-51",
    "name": "George Hemmings",
    "tag": "GH",
    "club": "AVL",
    "pos": "MID",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.6
  },
  {
    "id": "alysson-52",
    "name": "Alysson",
    "tag": "AD",
    "club": "AVL",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "manzambi-53",
    "name": "Manzambi",
    "tag": "JM",
    "club": "AVL",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.5
  },
  {
    "id": "gomes-54",
    "name": "Gomes",
    "tag": "JG",
    "club": "AVL",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.03,
    "xa": 0.03,
    "own": 0.1
  },
  {
    "id": "watkins-55",
    "name": "Watkins",
    "tag": "OW",
    "club": "AVL",
    "pos": "FWD",
    "price": 8,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.43,
    "xa": 0.11,
    "own": 11.4
  },
  {
    "id": "abraham-56",
    "name": "Abraham",
    "tag": "TA",
    "club": "AVL",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.55,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "garnacho-160",
    "name": "Garnacho",
    "tag": "AG",
    "club": "AVL",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0.06,
    "xa": 0.24,
    "own": 0.7
  },
  {
    "id": "madjo-582",
    "name": "Madjo",
    "tag": "BM",
    "club": "AVL",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.7
  },
  {
    "id": "ruggeri-596",
    "name": "Ruggeri",
    "tag": "MR",
    "club": "AVL",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "suzuki-597",
    "name": "Suzuki",
    "tag": "ZS",
    "club": "AVL",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      1,
      1,
      2,
      5
    ],
    "xg": 0,
    "xa": 0,
    "xs": 0,
    "own": 0.1
  },
  {
    "id": "petrovi--57",
    "name": "Petrović",
    "tag": "ĐP",
    "club": "BOU",
    "pos": "GKP",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2.9,
    "own": 3.4
  },
  {
    "id": "forster-58",
    "name": "Forster",
    "tag": "FF",
    "club": "BOU",
    "pos": "GKP",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "xs": 0,
    "own": 3.2
  },
  {
    "id": "dennis-59",
    "name": "Dennis",
    "tag": "WD",
    "club": "BOU",
    "pos": "GKP",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "xs": 0,
    "own": 0.2
  },
  {
    "id": "hill-60",
    "name": "Hill",
    "tag": "JH",
    "club": "BOU",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0.11,
    "own": 0.9
  },
  {
    "id": "truffert-61",
    "name": "Truffert",
    "tag": "AT",
    "club": "BOU",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.02,
    "xa": 0.14,
    "own": 4.7
  },
  {
    "id": "diakit--62",
    "name": "Diakité",
    "tag": "BD",
    "club": "BOU",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "milosavljevi--63",
    "name": "Milosavljević",
    "tag": "VM",
    "club": "BOU",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "smith-64",
    "name": "Smith",
    "tag": "AS",
    "club": "BOU",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0.14,
    "own": 0.1
  },
  {
    "id": "j-araujo-65",
    "name": "J.Araujo",
    "tag": "JA",
    "club": "BOU",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "soler-66",
    "name": "Soler",
    "tag": "JS",
    "club": "BOU",
    "pos": "DEF",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.3
  },
  {
    "id": "rayan-67",
    "name": "Rayan",
    "tag": "RS",
    "club": "BOU",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.34,
    "xa": 0.14,
    "own": 2.9
  },
  {
    "id": "tavernier-68",
    "name": "Tavernier",
    "tag": "MT",
    "club": "BOU",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.2,
    "xa": 0.11,
    "own": 1.7
  },
  {
    "id": "scott-69",
    "name": "Scott",
    "tag": "AS",
    "club": "BOU",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.08,
    "xa": 0.05,
    "own": 1.5
  },
  {
    "id": "kluivert-70",
    "name": "Kluivert",
    "tag": "JK",
    "club": "BOU",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.16,
    "xa": 0,
    "own": 1.1
  },
  {
    "id": "cook-71",
    "name": "Cook",
    "tag": "LC",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0.09,
    "own": 0.1
  },
  {
    "id": "gannon-doak-72",
    "name": "Gannon-Doak",
    "tag": "BG",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0.73,
    "own": 0.1
  },
  {
    "id": "adams-73",
    "name": "Adams",
    "tag": "TA",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.09,
    "xa": 0.09,
    "own": 0.3
  },
  {
    "id": "brooks-74",
    "name": "Brooks",
    "tag": "DB",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.06,
    "xa": 0.19,
    "own": 0.1
  },
  {
    "id": "christie-75",
    "name": "Christie",
    "tag": "RC",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.16,
    "xa": 0.08,
    "own": 0
  },
  {
    "id": "t-th-a-76",
    "name": "Tóth.A",
    "tag": "AT",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "adli-77",
    "name": "Adli",
    "tag": "AA",
    "club": "BOU",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.21,
    "xa": 0.14,
    "own": 0.1
  },
  {
    "id": "kroupi-jr-78",
    "name": "Kroupi.Jr",
    "tag": "JK",
    "club": "BOU",
    "pos": "MID",
    "price": 7.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.6,
    "xa": 0,
    "own": 0.9
  },
  {
    "id": "evanilson-79",
    "name": "Evanilson",
    "tag": "FD",
    "club": "BOU",
    "pos": "FWD",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.17,
    "xa": 0.2,
    "own": 2.2
  },
  {
    "id": "enes-nal-80",
    "name": "Enes Ünal",
    "tag": "EÜ",
    "club": "BOU",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0.36,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "rodr-guez-81",
    "name": "Rodríguez",
    "tag": "ÁR",
    "club": "BOU",
    "pos": "FWD",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "silva-566",
    "name": "Silva",
    "tag": "AP",
    "club": "BOU",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.3
  },
  {
    "id": "sanchez-573",
    "name": "Sanchez",
    "tag": "JS",
    "club": "BOU",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      2,
      5,
      2,
      2
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "kelleher-82",
    "name": "Kelleher",
    "tag": "CK",
    "club": "BRE",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2.9,
    "own": 5.9
  },
  {
    "id": "valdimarsson-83",
    "name": "Valdimarsson",
    "tag": "HV",
    "club": "BRE",
    "pos": "GKP",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "xs": 1,
    "own": 0.1
  },
  {
    "id": "collins-84",
    "name": "Collins",
    "tag": "NC",
    "club": "BRE",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.03,
    "xa": 0.05,
    "own": 1.9
  },
  {
    "id": "van-den-berg-85",
    "name": "Van den Berg",
    "tag": "SV",
    "club": "BRE",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0.08,
    "own": 0.3
  },
  {
    "id": "lewis-potter-86",
    "name": "Lewis-Potter",
    "tag": "KL",
    "club": "BRE",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.12,
    "xa": 0.16,
    "own": 0.5
  },
  {
    "id": "ajer-87",
    "name": "Ajer",
    "tag": "KA",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0.08,
    "own": 2.6
  },
  {
    "id": "kayode-88",
    "name": "Kayode",
    "tag": "MK",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.02,
    "xa": 0.05,
    "own": 3.3
  },
  {
    "id": "henry-89",
    "name": "Henry",
    "tag": "RH",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0.12,
    "own": 0.3
  },
  {
    "id": "hickey-90",
    "name": "Hickey",
    "tag": "AH",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "pinnock-91",
    "name": "Pinnock",
    "tag": "EP",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "ji-soo-92",
    "name": "Ji-soo",
    "tag": "KJ",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "schuster-93",
    "name": "Schuster",
    "tag": "JS",
    "club": "BRE",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "schade-94",
    "name": "Schade",
    "tag": "KS",
    "club": "BRE",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.22,
    "xa": 0.14,
    "own": 3.5
  },
  {
    "id": "o-dango-95",
    "name": "O.Dango",
    "tag": "DO",
    "club": "BRE",
    "pos": "MID",
    "price": 6.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.24,
    "xa": 0.27,
    "own": 1.3
  },
  {
    "id": "damsgaard-96",
    "name": "Damsgaard",
    "tag": "MD",
    "club": "BRE",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.15,
    "xa": 0.15,
    "own": 0.6
  },
  {
    "id": "jensen-97",
    "name": "Jensen",
    "tag": "MJ",
    "club": "BRE",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.1,
    "xa": 0.07,
    "own": 0.2
  },
  {
    "id": "janelt-98",
    "name": "Janelt",
    "tag": "VJ",
    "club": "BRE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.05,
    "xa": 0.21,
    "own": 0.1
  },
  {
    "id": "milambo-99",
    "name": "Milambo",
    "tag": "AM",
    "club": "BRE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "carvalho-100",
    "name": "Carvalho",
    "tag": "FF",
    "club": "BRE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.76,
    "xa": 0,
    "own": 0
  },
  {
    "id": "yarmoliuk-102",
    "name": "Yarmoliuk",
    "tag": "YY",
    "club": "BRE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.03,
    "xa": 0.09,
    "own": 1.4
  },
  {
    "id": "dasilva-103",
    "name": "Dasilva",
    "tag": "JD",
    "club": "BRE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "anthony-105",
    "name": "Anthony",
    "tag": "JA",
    "club": "BRE",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "thiago-106",
    "name": "Thiago",
    "tag": "IN",
    "club": "BRE",
    "pos": "FWD",
    "price": 8,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0.51,
    "xa": 0.02,
    "own": 17.7
  },
  {
    "id": "furo-107",
    "name": "Furo",
    "tag": "KF",
    "club": "BRE",
    "pos": "FWD",
    "price": 4.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.8
  },
  {
    "id": "wilson-108",
    "name": "Wilson",
    "tag": "CW",
    "club": "BRE",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.3
  },
  {
    "id": "sangar--565",
    "name": "Sangaré",
    "tag": "MS",
    "club": "BRE",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      3,
      1,
      1
    ],
    "xg": 0,
    "xa": 0,
    "own": 2.9
  },
  {
    "id": "verbruggen-109",
    "name": "Verbruggen",
    "tag": "BV",
    "club": "BHA",
    "pos": "GKP",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2.8,
    "own": 20.1
  },
  {
    "id": "steele-111",
    "name": "Steele",
    "tag": "JS",
    "club": "BHA",
    "pos": "GKP",
    "price": 4,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "xs": 0,
    "own": 4.2
  },
  {
    "id": "f-kad-o-lu-113",
    "name": "F.Kadıoğlu",
    "tag": "FK",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.02,
    "xa": 0.05,
    "own": 3.1
  },
  {
    "id": "boscagli-114",
    "name": "Boscagli",
    "tag": "OB",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0.1,
    "own": 0.2
  },
  {
    "id": "de-cuyper-115",
    "name": "De Cuyper",
    "tag": "MD",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.11,
    "xa": 0.16,
    "own": 1.7
  },
  {
    "id": "dunk-116",
    "name": "Dunk",
    "tag": "LD",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.03,
    "xa": 0.03,
    "own": 0.9
  },
  {
    "id": "coppola-117",
    "name": "Coppola",
    "tag": "DC",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "igor-118",
    "name": "Igor",
    "tag": "ID",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "costinha-119",
    "name": "Costinha",
    "tag": "JL",
    "club": "BHA",
    "pos": "DEF",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "svoboda-120",
    "name": "Svoboda",
    "tag": "MS",
    "club": "BHA",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "mitoma-121",
    "name": "Mitoma",
    "tag": "MK",
    "club": "BHA",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.13,
    "xa": 0.04,
    "own": 0.1
  },
  {
    "id": "minteh-122",
    "name": "Minteh",
    "tag": "YM",
    "club": "BHA",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.1,
    "xa": 0.26,
    "own": 0.2
  },
  {
    "id": "hinshelwood-123",
    "name": "Hinshelwood",
    "tag": "JH",
    "club": "BHA",
    "pos": "MID",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.18,
    "xa": 0.22,
    "own": 0.4
  },
  {
    "id": "gro--124",
    "name": "Groß",
    "tag": "PG",
    "club": "BHA",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.05,
    "xa": 0.28,
    "own": 13.5
  },
  {
    "id": "georginio-125",
    "name": "Georginio",
    "tag": "GR",
    "club": "BHA",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.13,
    "xa": 0.22,
    "own": 1
  },
  {
    "id": "o-riley-126",
    "name": "O'Riley",
    "tag": "MO",
    "club": "BHA",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.38,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "gomez-127",
    "name": "Gomez",
    "tag": "DG",
    "club": "BHA",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.18,
    "xa": 0.04,
    "own": 3.1
  },
  {
    "id": "buonanotte-128",
    "name": "Buonanotte",
    "tag": "FB",
    "club": "BHA",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "ayari-129",
    "name": "Ayari",
    "tag": "YA",
    "club": "BHA",
    "pos": "MID",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.12,
    "xa": 0.16,
    "own": 0.7
  },
  {
    "id": "wieffer-130",
    "name": "Wieffer",
    "tag": "MW",
    "club": "BHA",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.08,
    "xa": 0.16,
    "own": 0.3
  },
  {
    "id": "baleba-131",
    "name": "Baleba",
    "tag": "CB",
    "club": "BHA",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "howell-132",
    "name": "Howell",
    "tag": "HH",
    "club": "BHA",
    "pos": "MID",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "watson-133",
    "name": "Watson",
    "tag": "TW",
    "club": "BHA",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "oriola-134",
    "name": "Oriola",
    "tag": "NO",
    "club": "BHA",
    "pos": "MID",
    "price": 4.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "yohanna-135",
    "name": "Yohanna",
    "tag": "ZY",
    "club": "BHA",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.1
  },
  {
    "id": "tzimas-137",
    "name": "Tzimas",
    "tag": "ST",
    "club": "BHA",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.58,
    "xa": 0.58,
    "own": 0
  },
  {
    "id": "kostoulas-138",
    "name": "Kostoulas",
    "tag": "CK",
    "club": "BHA",
    "pos": "FWD",
    "price": 5.5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0.44,
    "xa": 0.22,
    "own": 0.2
  },
  {
    "id": "ferguson-139",
    "name": "Ferguson",
    "tag": "EF",
    "club": "BHA",
    "pos": "FWD",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0
  },
  {
    "id": "struijk-328",
    "name": "Struijk",
    "tag": "PS",
    "club": "BHA",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0.03,
    "own": 0.2
  },
  {
    "id": "vuskovic-504",
    "name": "Vuskovic",
    "tag": "LV",
    "club": "BHA",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 2.7
  },
  {
    "id": "david-594",
    "name": "David",
    "tag": "PD",
    "club": "BHA",
    "pos": "FWD",
    "price": 6,
    "form": 0,
    "fdr": 1,
    "fdrs": [
      1,
      5,
      5,
      1,
      4
    ],
    "xg": 0,
    "xa": 0,
    "own": 0.2
  },
  {
    "id": "rogers-40",
    "name": "Rogers",
    "tag": "MR",
    "club": "CHE",
    "pos": "MID",
    "price": 7.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.23,
    "xa": 0.19,
    "own": 25.7
  },
  {
    "id": "henderson-101",
    "name": "Henderson",
    "tag": "JH",
    "club": "CHE",
    "pos": "MID",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.04,
    "xa": 0.12,
    "own": 0
  },
  {
    "id": "welbeck-136",
    "name": "Welbeck",
    "tag": "DW",
    "club": "CHE",
    "pos": "FWD",
    "price": 6,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.44,
    "xa": 0.03,
    "own": 1.9
  },
  {
    "id": "s-nchez-140",
    "name": "Sánchez",
    "tag": "RL",
    "club": "CHE",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0,
    "xa": 0,
    "xs": 2.9,
    "own": 2.3
  },
  {
    "id": "j-rgensen-141",
    "name": "Jörgensen",
    "tag": "FJ",
    "club": "CHE",
    "pos": "GKP",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0,
    "xa": 0,
    "xs": 1.9,
    "own": 0
  },
  {
    "id": "james-142",
    "name": "James",
    "tag": "RJ",
    "club": "CHE",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.08,
    "xa": 0.23,
    "own": 9.3
  },
  {
    "id": "chalobah-143",
    "name": "Chalobah",
    "tag": "TC",
    "club": "CHE",
    "pos": "DEF",
    "price": 5.5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.08,
    "xa": 0.03,
    "own": 0.4
  },
  {
    "id": "gusto-144",
    "name": "Gusto",
    "tag": "MG",
    "club": "CHE",
    "pos": "DEF",
    "price": 5,
    "form": 0,
    "fdr": 4,
    "fdrs": [
      4,
      1,
      1,
      1,
      3
    ],
    "xg": 0.07,
    "xa": 0.1,
    "own": 1.1
  }
];
